In [1]:
! pip install numpy

In [2]:
import numpy as np

## 1. Creating Arrays

In [3]:
# 1D array
arr1 =np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# reshaping the array
# 2D array
arr2 =np.array([1,2,3,4,5])
arr2.reshape(1,5)

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape)
print(arr2)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# in-built functions
np.arange(0,10,2)
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 2. Vectorized Operations

In [8]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ", arr1+arr2)
print("Subtraction: ", arr1-arr2)
print("vise versa")

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
vise versa


In [9]:
# universal funcions
arr3 = np.array([2,3,4,5,6])

print(np.sqrt(arr3))
print(np.exp(arr3))
print(np.sin(arr3))
print(np.log(arr3))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## 3. Array slicing and indexing

In [10]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr4)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(arr4[0])
print(arr4[0,0])

[1 2 3 4]
1


In [12]:
print(arr4[1:])
print(arr4[1:,2:])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [13]:
print(arr4[0:2,2:])

[[3 4]
 [7 8]]


In [14]:
print(arr4[1:,1:3])

[[ 6  7]
 [10 11]]


In [15]:
# Modify array elements
arr4[0,0] = 100
print(arr4)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## 4. Statistical Concepts -- Normalization

In [16]:
data = np.array([10,20,30,40,50])

mean = np.mean(data)
std_dev = np.std(data)

In [17]:
normalized_data = (data-mean)/std_dev
print(f"Normalized Data: {normalized_data}")

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [18]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Standard Deviation: {np.std(data)}")
print(f"Variance: {np.var(data)}")

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [24]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=7)]

array([5, 6, 7])